# Generated by Django 2.2.6 on 2020-01-01 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumb_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_image', models.ImageField(blank=True, null=True, upload_to='images/thumb/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Images',
            new_name='LargeImage',
        ),
        migrations.RemoveField(
            model_name='item',
            name='large_images',
        ),
        migrations.DeleteModel(
            name='Thumb_Images',
        ),
        migrations.AddField(
            model_name='thumb_image',
            name='item_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Item'),
        ),
    ]
