# Generated by Django 2.2.6 on 2020-04-17 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large_image', models.ImageField(blank=True, null=True, upload_to='images/large/')),
                ('thumb_image', models.ImageField(blank=True, null=True, upload_to='images/thumb/')),
                ('item_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Item')),
            ],
        ),
        migrations.RemoveField(
            model_name='thumb_image',
            name='item_instance',
        ),
        migrations.DeleteModel(
            name='LargeImage',
        ),
        migrations.DeleteModel(
            name='Thumb_Image',
        ),
    ]
