# Generated by Django 2.2.6 on 2020-04-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200417_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='colors',
            field=models.BooleanField(default=False, help_text='click the checkbox if this is a color variation'),
        ),
    ]
