# Generated by Django 2.2.6 on 2020-01-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200101_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='avaliability',
            field=models.CharField(choices=[('1', 'IN STOCK'), ('0', 'OUT OF STOCK')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity_available',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Discount price'),
        ),
        migrations.AlterField(
            model_name='largeimage',
            name='large_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/large/'),
        ),
    ]
