# Generated by Django 2.2.6 on 2020-01-12 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_review_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
    ]
